sonar.projectKey=lduchosal_semacli
sonar.organization=lduchosal

sonar.sources=semacli
sonar.tests=tests

sonar.python.version=3.10,3.11,3.12,3.13
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=dist/**,build/**,**/__pycache__/**,interrogate_badge.svg,doc/**
sonar.coverage.exclusions=tests/**
